version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "Area: Dependencies"
      - "Area: Frontend"
    reviewers: ["dawnofmidnight"]
    assignees: ["dawnofmidnight"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Area: Dependencies"
      - "Area: Backend"
    reviewers: ["kronifer"]
    assignees: ["kronifer"]
 
