version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "Area: Dependencies"
      - "Area: Frontend"
    reviewers: ["dawnofmidnight"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Area: Dependencies"
      - "Area: Backend"
    reviewers: ["kronifer"]
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"