version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "daily"
  #   labels:
  #     - "Area: Dependencies"
  #     - "Area: Frontend"
  #   reviewers: ["dawnofmidnight"]
  #   assignees: ["dawnofmidnight"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Area: Dependencies"
      - "Area: Backend"
    reviewers: ["kronifer"]
    assignees: ["kronifer"]
 
