version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "Area: Dependencies"
      - "Area: Frontend"
    reviewers: ["dawnofmidnight"]
    assignees: ["dawnofmidnight"]
 
