version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    assignees: "dawnofmidnight"
    labels:
      - "Area: Dependencies"
      - "Area: Frontend"
    reviewers: "dawnofmidnight"
 
