name = "frontend"
type = "webpack"
target_type = "webpack"
account_id = "b5ddf6c30816fa7e0fe47ba4276a7d0b"
zone_id = "f5764424953c03a7ac920a4a16379a70"
routes = ["catcord.codes/*", "www.catcord.codes/*"]
workers_dev = true

[site]
bucket = "dist"
entry-point = "workers-site"