version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./catcord/.env
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: gunicorn catcord.__main__:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0
        volumes:
            - .:/catcord
        env_file:
            - ./catcord/.env
        ports:
            - "8000:8000"

volumes:
    postgres_data: