services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres

  redis:
    image: "redis:alpine"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./:/backend/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
      - redis
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./:/frontend/app
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:8000

volumes:
  postgres_data:
