services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=catcord
      - POSTGRES_USER=catcord
      - POSTGRES_PASSWORD=catcord  
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
