version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: uvicorn catcord.__main__:app --host 0.0.0.0
        volumes:
            - .:/catcord
        ports:
            - "8000:8000"
