CREATE TABLE USERS(
    ID TEXT PRIMARY KEY,
    TOKEN TEXT NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL

);

CREATE TABLE SERVERS(
    SERVER_ID TEXT PRIMARY KEY,
    OWNER_ID TEXT NOT NULL,
    SERVER_NAME TEXT NOT NULL,
    FOREIGN KEY(OWNER_ID) REFERENCES USERS(ID)
);

CREATE TABLE MESSAGES(
    MESSAGE_ID TEXT PRIMARY KEY,
    TIMESENT BIGINT NOT NULL,
    SENDER_ID TEXT NOT NULL,
    SERVER_ID TEXT NOT NULL,
    MESSAGE_CONTENT VARCHAR(1000) NOT NULL,
    FOREIGN KEY(SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(SERVER_ID) REFERENCES SERVERS(SERVER_ID)
)
