name = "catcord"
type = "webpack"
account_id = "b5ddf6c30816fa7e0fe47ba4276a7d0b"
route = ""
usage_model = ""
workers_dev = true
target_type = "webpack"

[site]
bucket = "build"
entry-point = "workers-site"

[env.production]
routes = ["catcord.codes/*", "www.catcord.codes/*"]
zone_id = "f5764424953c03a7ac920a4a16379a70"